baseURL = 'https://kjg-dossenheim.org'
languageCode = 'de-DE'
defaultContentLanguage = 'de'
title = 'KjG Dossenheim'

enableRobotsTXT = true
pluralizelisttitles = false
disableKinds = ['taxonomy', 'term']


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true


[params]
  description = "Die KjG Dossenheim vertritt die Interessen der Kinder und Jugendlichen in der katholischen Gemeinden der Stadt Dossenheim"
  facebook = "kjg.dossenheim"
  instagram = "kjg.dossenheim"
  images = ['/images/opengraph.svg']
  title = "KjG Dossenheim"

[menu]
[[menu.main]]
  name = 'Startseite'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Aktionen'
  identifier = "aktionen"
[[menu.main]]
    identifier = "martinszug"
    name = "Martinszug"
    url = "/martinszug/"
    parent = "aktionen"
[[menu.main]]
    identifier = "sommerfreizeit"
    name = "Sommerfreizeit"
    url = "/sommerfreizeit/"
    parent = "aktionen"
[[menu.main]]
    identifier = "tannenbaumaktion"
    name = "Tannenbaumaktion"
    url = "/tannenbaumaktion/"
    parent = "aktionen"
[[menu.main]]
    identifier = "adventsmarkt"
    name = "Adventsmarkt"
    url = "/adventsmarkt/"
    parent = "aktionen"
[[menu.main]]
    identifier = "72stunden"
    name = "72-Stunden-Aktion"
    url = "/72stunden/"
    parent = "aktionen"
[[menu.main]]
  name = 'Über uns'
  url = '/about/'
 [[menu.main]]
  name = 'Kontakt'
  url = '/kontakt/'



[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false