baseURL = 'https://kjg-dossenheim.org'
languageCode = 'de-DE'
defaultContentLanguage = 'de'
title = 'KjG Dossenheim'
copyright = 'KjG Dossenheim'
enableRobotsTXT = true
pluralizelisttitles = false

[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[params]
  Description = "Die KjG Dossenheim vertritt die Interessen der Kinder und Jugendlichen in der katholischen Gemeinden der Stadt Dossenheim"

[menu]
[[menu.main]]
  name = 'Startseite'
  url = '/'
  weight = 10
[[menu.main]]
  identifier = "aktionen"
  name = 'Aktionen'
  url = '/aktionen/'
  weight = 20
[[menu.main]]
    identifier = "sommerfreizeit"
    name = "Sommerfreizeit"
    url = "/sommerfreizeit/"
    parent = "aktionen"
    weight = 1
[[menu.main]]
    identifier = "anmeldung"
    name = "Anmeldung"
    url = "/sommerfreizeit/anmeldung/"
    parent = "sommerfreizeit"
    weight = 1
[[menu.main]]
    identifier = "tannenbaumaktion"
    name = "Tannenbaumaktion"
    url = "/tannenbaumaktion/"
    parent = "aktionen"
    weight = 2
[[menu.main]]
  name = 'Über uns'
  url = '/about/'
  weight = 25
 [[menu.main]]
  name = 'Kontakt'
  url = '/kontakt/'
  weight = 30



[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false